package unimap;

import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

public class Unimap_1 extends javax.swing.JFrame implements java.awt.event.MouseListener{

    String button = "";
    
    Loader Loader;
    
    JButton b1, b2, b3, b4, b5, b6, b7;
    
    public void ButtonsLeft(){
        
        // Texto a los botones.
        b1 = new JButton("Auditorios");
        b2 = new JButton("Baños");
        b3 = new JButton("Bibliotecas");
        b4 = new JButton("Coordinaciones");
        b5 = new JButton("Papelerias");
        b6 = new JButton("Puntos de Interes");
        b7 = new JButton("Servicios");
        
        // Nombre a cada boton.
        b1.setName("Auditorios");
        b2.setName("Baños");
        b3.setName("Bibliotecas");
        b4.setName("Coordinaciones");
        b5.setName("Papelerias");
        b6.setName("Puntos de Interes");
        b7.setName("Servicios");
        
        // Tamaño de cada boton.
        b1.setSize(145,109);
        b2.setSize(145,109);
        b3.setSize(145,109);
        b4.setSize(145,109);
        b5.setSize(145,109);
        b6.setSize(145,109);
        b7.setSize(145,109);
        
        // Creación de un GridLayout
        GridLayout gl = new GridLayout();
        gl.setColumns(1);
        gl.setRows(7);
        
        // Integrando componente Grid al Panel "pane1"
        pane1.setLayout(gl);
        
        // Integrando componente Buttons al Panel "pane1" y otorgando Listener
        pane1.add(b1).addMouseListener(this); pane1.add(b2).addMouseListener(this);
        pane1.add(b3).addMouseListener(this); pane1.add(b4).addMouseListener(this); 
        pane1.add(b5).addMouseListener(this); pane1.add(b6).addMouseListener(this);
        pane1.add(b7).addMouseListener(this);
        
    }
    
    public Unimap_1() {
        initComponents();
        
        ButtonsLeft();
        setLocationRelativeTo(null);
        // MouseListener a cada panel
        pane1.addMouseListener(this);
        pane2.addMouseListener(this);
        
        Split_uni.setDividerSize(0);
        Split_uni.setOneTouchExpandable(false);
        
        Loader = new Loader();
    }

    @Override
    public void mouseClicked(MouseEvent me) {
        System.out.println("You clicked:"+me.getComponent().getName());
        
        pane2.removeAll();
        
        String dato = me.getComponent().getName();
        
        if (!dato.equals(button)){
            switch(dato){
                case "Auditorios":
                    PanelAuditorios a = new PanelAuditorios();
                    pane2.add(a);
                    break;
                case "Baños":
                    PanelBaños ba = new PanelBaños(Loader);
                    pane2.add(ba);
                    break;
                case "Bibliotecas":
                    PanelBibliotecas bi = new PanelBibliotecas(Loader);
                    pane2.add(bi);
                    break;
                case "Papelerias":
                    PanelPapelerias pa = new PanelPapelerias(Loader);
                    pane2.add(pa);
                    break;
                case "Coordinaciones":
                    PanelCoordinaciones co = new PanelCoordinaciones(Loader);
                    pane2.add(co);
                    break;
                case "Puntos de Interes":
                    PanelPuntosInteres pi= new PanelPuntosInteres(Loader);
                    pane2.add(pi);
                    break;
                case "Servicios":
                    PanelServicios s = new PanelServicios(Loader);
                    pane2.add(s);
                    break;
            }
            button = me.getComponent().getName();
        }else{
            System.out.println("Entra");
            button = "";
        }
        pane2.revalidate();
        pane2.repaint();
    }

    @Override
    public void mousePressed(MouseEvent me) {}

    @Override
    public void mouseReleased(MouseEvent me) {}

    @Override
    public void mouseEntered(MouseEvent me) {}

    @Override
    public void mouseExited(MouseEvent me) {}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Split_uni = new javax.swing.JSplitPane();
        pane1 = new javax.swing.JPanel();
        pane2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));

        Split_uni.setMaximumSize(new java.awt.Dimension(1024, 768));
        Split_uni.setMinimumSize(new java.awt.Dimension(1024, 768));
        Split_uni.setPreferredSize(new java.awt.Dimension(1024, 768));

        pane1.setBackground(new java.awt.Color(204, 204, 204));
        pane1.setMaximumSize(new java.awt.Dimension(145, 768));
        pane1.setMinimumSize(new java.awt.Dimension(145, 768));

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        Split_uni.setLeftComponent(pane1);

        pane2.setMaximumSize(new java.awt.Dimension(879, 768));
        pane2.setMinimumSize(new java.awt.Dimension(879, 768));
        pane2.setLayout(new java.awt.CardLayout());
        Split_uni.setRightComponent(pane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Split_uni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Split_uni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unimap_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unimap_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unimap_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unimap_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unimap_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Split_uni;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    // End of variables declaration//GEN-END:variables
}
