/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import java.awt.event.MouseEvent;

/**
 *
 * @author usuariolocal
 */
public class auditorios extends javax.swing.JPanel {

    /**
     * Creates new form auditorios
     */
    public auditorios() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        pane2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(879, 768));
        setMinimumSize(new java.awt.Dimension(879, 768));

        split.setDividerLocation(145);
        split.setMaximumSize(new java.awt.Dimension(879, 768));
        split.setMinimumSize(new java.awt.Dimension(879, 768));
        split.setPreferredSize(new java.awt.Dimension(879, 768));

        pane2.setDoubleBuffered(false);
        pane2.setMaximumSize(new java.awt.Dimension(145, 768));
        pane2.setMinimumSize(new java.awt.Dimension(145, 768));

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        split.setLeftComponent(pane2);

        jSplitPane1.setDividerLocation(448);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(734, 768));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(734, 768));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(734, 768));

        jSplitPane2.setDividerLocation(734);
        jSplitPane2.setMaximumSize(new java.awt.Dimension(200, 734));
        jSplitPane2.setMinimumSize(new java.awt.Dimension(200, 734));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(200, 734));
        jSplitPane1.setTopComponent(jSplitPane2);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(734, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(734, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(734, 400));
        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane3.setDividerLocation(367);
        jSplitPane3.setMaximumSize(new java.awt.Dimension(320, 240));
        jSplitPane3.setMinimumSize(new java.awt.Dimension(320, 240));
        jSplitPane3.setPreferredSize(new java.awt.Dimension(320, 240));

        jPanel4.setDoubleBuffered(false);
        jPanel4.setMaximumSize(new java.awt.Dimension(367, 368));
        jPanel4.setMinimumSize(new java.awt.Dimension(367, 368));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jSplitPane3.setLeftComponent(jPanel4);

        jPanel5.setDoubleBuffered(false);
        jPanel5.setMaximumSize(new java.awt.Dimension(367, 368));
        jPanel5.setMinimumSize(new java.awt.Dimension(367, 368));
        jPanel5.setPreferredSize(new java.awt.Dimension(367, 368));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel5);

        jSplitPane1.setRightComponent(jSplitPane3);

        split.setRightComponent(jSplitPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClicked(MouseEvent evt){
        System.out.println("entra");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JPanel pane2;
    public static javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables
}
