/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;


import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author usuariolocal
 */
public class base extends javax.swing.JFrame implements java.awt.event.MouseListener{

    /**
     * Creates new form base
     */
    String button = "";
    
    JLabel label;
    
    JButton b1;
    JButton b2;
    JButton b3;
    JButton b4;
    JButton b5;
    JButton b6;
    JButton b7;
    
    public void PrincipalButtons(){
        
        // Texto a los botones.
        b1 = new JButton("Auditorios");
        b2 = new JButton("Baños");
        b3 = new JButton("Bibliotecas");
        b4 = new JButton("Coordinaciones");
        b5 = new JButton("Papelerias");
        b6 = new JButton("Puntos de Interes");
        b7 = new JButton("Servicios");
        
        // Nombre a cada boton.
        b1.setName("Auditorios");
        b2.setName("Baños");
        b3.setName("Bibliotecas");
        b4.setName("Coordinaciones");
        b5.setName("Papelerias");
        b6.setName("Puntos de Interes");
        b7.setName("Servicios");
        
        // Tamaño de cada boton.
        b1.setSize(145,80);
        b2.setSize(145,80);
        b3.setSize(145,80);
        b4.setSize(145,80);
        b5.setSize(145,80);
        b6.setSize(145,80);
        b7.setSize(145,80);
        
        // Creación de un GridLayout
        GridLayout gl = new GridLayout();
        gl.setColumns(1);
        gl.setRows(7);
        
        // Integrando componente Grid al Panel "pane1"
        pane1.setLayout(gl);
        
        // Integrando componente Buttons al Panel "pane1" y otorgando Listener
        pane1.add(b1).addMouseListener(this); pane1.add(b2).addMouseListener(this);
        pane1.add(b3).addMouseListener(this); pane1.add(b4).addMouseListener(this); 
        pane1.add(b5).addMouseListener(this); pane1.add(b6).addMouseListener(this);
        pane1.add(b7).addMouseListener(this);
        
        Split.setOneTouchExpandable(false);
    }
    
    public base() {
        initComponents();
        
        // Inicializar cada boton
        PrincipalButtons();
        
        label = new JLabel();
        label.setIcon(mapa.getIcon());
        
        // MouseListener a cada panel
        pane1.addMouseListener(this);
        pane2.addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Split = new javax.swing.JSplitPane();
        pane1 = new javax.swing.JPanel();
        pane2 = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(879, 768));

        Split.setDividerLocation(145);
        Split.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Split.setMaximumSize(new java.awt.Dimension(1040, 768));
        Split.setMinimumSize(new java.awt.Dimension(1040, 768));
        Split.setPreferredSize(new java.awt.Dimension(1040, 768));

        pane1.setMaximumSize(new java.awt.Dimension(145, 768));
        pane1.setMinimumSize(new java.awt.Dimension(145, 768));

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        Split.setLeftComponent(pane1);

        pane2.setMaximumSize(new java.awt.Dimension(879, 768));
        pane2.setMinimumSize(new java.awt.Dimension(879, 768));
        pane2.setPreferredSize(new java.awt.Dimension(879, 768));
        pane2.setLayout(new java.awt.CardLayout());

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mapa.jpg"))); // NOI18N
        pane2.add(mapa, "card2");

        Split.setRightComponent(pane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Split, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Split, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Split;
    private javax.swing.JLabel mapa;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
        System.out.println("You clicked:"+me.getComponent().getName());
        
        
        pane2.removeAll();
        
        if (!me.getComponent().getName().equals(button)){
            switch(me.getComponent().getName()){
                case "Auditorios":
                    auditorios a = new auditorios();
                    pane2.add(a);
                    break;
                case "Baños":
                    baños ba = new baños();
                    pane2.add(ba);
                    break;
                case "Bibliotecas":
                    bibliotecas bi = new bibliotecas();
                    pane2.add(bi);
                    break;
                case "Papelerias":
                    centrocopy pa = new centrocopy();
                    pane2.add(pa);
                    break;
                case "Coordinaciones":
                    coordinaciones co = new coordinaciones();
                    pane2.add(co);
//                    co.list.addMouseListener(this);
                    break;
                case "Puntos de Interes":
                    puntointeres pi= new puntointeres();
                    pane2.add(pi);
                    break;
                case "Servicios":
                    servicios s = new servicios();
                    pane2.add(s);
                    break;
            }
            button = me.getComponent().getName();
        }else{
            System.out.println("Entra");
            button = "";
            pane2.add(label);
        }
        pane2.revalidate();
        pane2.repaint();
    }
    
    @Override
    public void mousePressed(MouseEvent me) {
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }
}
