/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.SpinnerModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author usuariolocal
 */
public class coordinaciones extends javax.swing.JPanel {

    /**
     * Creates new form coordinaciones
     */
    
    public void SecondaryButtons(){
        
//        
//        list.setValue("Coordinación académica");
//        list.setValue(" ");
//        list.setValue("Div. Humanidades y Bellas Artes");
//        list.setValue("Arquitectura");
        
//        list.addElement("Diseño Gráfico");
//        list.addElement("Artes Escenicas");
//        list.addElement("Artes Plasticas");
//        list.addElement(" ");
//        list.addElement("Div. Ciencias Económicas y Administraticas");
//        list.addElement("Contaduría Pública");
//        list.addElement("Administración");
//        list.addElement("Mercadotecnia");
//        list.addElement("Turismo");
//        list.addElement("Economía");
//        list.addElement("Finanzas");
//        list.addElement("Negocios y Comercio Internacional");
//        list.addElement(" ");
//        list.addElement("Div. Ingeniería");
//        list.addElement("Civil");
//        list.addElement("Mecatrónica");
//        list.addElement("Sistemas de la Información");
//        list.addElement("Minero");
//        list.addElement("Materiales");
//        list.addElement("Energías Renovables");
//        list.addElement("Metalurgía");
//        list.addElement("Química");
//        list.addElement(" ");
//        list.addElement("Sociología");
//        list.addElement("Administración Pública");
//        list.addElement("Psicología");
//        list.addElement("Ciencias de la Comunicación");
//        list.addElement("Historía");
//        list.addElement("Antropología");
//        list.addElement("Trabajo Social");
//        list.addElement(" ");
//        list.addElement("Div. Ciencias Exactas y Naturales");
//        list.addElement("Física");
//        list.addElement("Matemáticas");
//        list.addElement("Ciencias de la Computación");
//        list.addElement("Tecnología Electrónica");
        
//        list2.setModel((SpinnerModel) list);
        
        
    }
    
    public coordinaciones() {
        initComponents();
        
        SecondaryButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(879, 768));
        setMinimumSize(new java.awt.Dimension(879, 768));

        jSplitPane4.setDividerLocation(145);
        jSplitPane4.setMaximumSize(new java.awt.Dimension(879, 768));
        jSplitPane4.setMinimumSize(new java.awt.Dimension(879, 768));
        jSplitPane4.setPreferredSize(new java.awt.Dimension(879, 768));

        jSplitPane1.setDividerLocation(448);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(734);
        jSplitPane2.setMaximumSize(new java.awt.Dimension(200, 734));
        jSplitPane2.setMinimumSize(new java.awt.Dimension(200, 734));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(200, 734));
        jSplitPane1.setTopComponent(jSplitPane2);
        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane3.setDividerLocation(367);
        jSplitPane3.setMaximumSize(new java.awt.Dimension(320, 240));
        jSplitPane3.setMinimumSize(new java.awt.Dimension(320, 240));
        jSplitPane3.setPreferredSize(new java.awt.Dimension(320, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jSplitPane3.setLeftComponent(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel5);

        jSplitPane1.setRightComponent(jSplitPane3);

        jSplitPane4.setRightComponent(jSplitPane1);

        list.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        list.setMaximumSize(new java.awt.Dimension(145, 768));
        list.setMinimumSize(new java.awt.Dimension(145, 768));
        list.setPreferredSize(new java.awt.Dimension(145, 768));
        jScrollPane2.setViewportView(list);

        jSplitPane4.setLeftComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JList<String> list;
    // End of variables declaration//GEN-END:variables
}
